In [1]:
!nvidia-smi

Fri Oct 14 16:57:17 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.40       Driver Version: 517.40       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   67C    P0    47W /  N/A |   3951MiB /  4096MiB |     46%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
!pip install --upgrade albumentations

In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import cv2
from pylab import rcParams
from tqdm import tqdm
import matplotlib.pyplot as plt
from matplotlib import rc
from pandas.plotting import register_matplotlib_converters
import albumentations as A
import random


In [1]:
import cv2

# rgb 이미지 불러오기
rgb_image = cv2.imread('C:/A/VinBigData/data_png_512/train/0a0ac65c40a9ac441651e4bfbde03c4e.png')

# rgb 이미지 보기
cv2.imshow('111', rgb_image)


: 

In [3]:
cv2.waitKey(0) 

# gray_scale 이미지 불러오기
gray_image = cv2.imread('C:/A/VinBigData/data_png_512/train/0a0ac65c40a9ac441651e4bfbde03c4e.png', 0) # 인수를 0으로 전달하면 gray 이미지가 로드된다.

# gray 이미지 보기
cv2.imshow('gray_image', gray_image)
cv2.waitKey(0)


error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1333: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'


In [8]:
import albumentations as A
import cv2

# Declare an augmentation pipeline
transform = A.Compose([
    A.RandomCrop(width=256, height=256),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
])

# Read an image with OpenCV and convert it to the RGB colorspace
image = cv2.imread("C:/A/VinBigData/data_png_512/train/0a0ac65c40a9ac441651e4bfbde03c4e.png")
#image = cv2.imread("C:/A/VinBigData/data_dicom/train1000/0a0ac65c40a9ac441651e4bfbde03c4e.dicom")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Augment an image
transformed = transform(image=image)
transformed_image = transformed["image"]

In [26]:
for i,k in enumerate(transformed['image']):
    if(i==1):
        print(i,k)
        print(k.shape)
        cv2.imshow('image',k)
        break

1 [[126 126 126]
 [129 129 129]
 [130 130 130]
 [129 129 129]
 [128 128 128]
 [131 131 131]
 [128 128 128]
 [127 127 127]
 [125 125 125]
 [124 124 124]
 [119 119 119]
 [114 114 114]
 [113 113 113]
 [117 117 117]
 [113 113 113]
 [106 106 106]
 [104 104 104]
 [103 103 103]
 [104 104 104]
 [104 104 104]
 [103 103 103]
 [107 107 107]
 [122 122 122]
 [133 133 133]
 [132 132 132]
 [125 125 125]
 [123 123 123]
 [132 132 132]
 [149 149 149]
 [167 167 167]
 [175 175 175]
 [177 177 177]
 [178 178 178]
 [179 179 179]
 [179 179 179]
 [173 173 173]
 [170 170 170]
 [164 164 164]
 [163 163 163]
 [160 160 160]
 [156 156 156]
 [159 159 159]
 [159 159 159]
 [161 161 161]
 [163 163 163]
 [171 171 171]
 [178 178 178]
 [178 178 178]
 [173 173 173]
 [168 168 168]
 [157 157 157]
 [132 132 132]
 [112 112 112]
 [112 112 112]
 [119 119 119]
 [122 122 122]
 [124 124 124]
 [124 124 124]
 [124 124 124]
 [124 124 124]
 [126 126 126]
 [127 127 127]
 [127 127 127]
 [126 126 126]
 [124 124 124]
 [131 131 131]
 [149 14

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1267: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
